### ISSUE TITLE
Problem With Reloading Init File

### ISSUE THREAD

**Issue by eeriemyxi** [skissue/meow-tree-sitter#2]
![image](https://github.com/user-attachments/assets/604c85af-f611-4517-8bc9-29a4bdf97886)

Reloading the init file multiple times results in `meow-tree-sitter-register-defaults` getting evaluated multiple times. 
```lisp
(use-package meow-tree-sitter
  :ensure t
  :config
  (meow-tree-sitter-register-defaults))
```
This can be fixed with something like this:
```lisp
(use-package meow-tree-sitter
  :ensure t
  :config
  (unless (featurep 'meow-tree-sitter-configured)
    (meow-tree-sitter-register-defaults)
    (provide 'meow-tree-sitter-configured)))
```

But I believe that it should be something that the package itself does for me. I have never encountered this kind of behavior with other plugins.

**Comment by skissue** [comment]
Thanks for the catch! Unfortunately, I don't use Meow anymore, so I can't really test this easily. Would you be willing to try c62179af4c306209398d3dc52c2f011eb78382f1 and see if it resolves this issue?

**Comment by eeriemyxi** [comment]
![image](https://github.com/user-attachments/assets/65fe2c21-c56a-4139-9fdb-78b59fc568e8)
Seems to work.

**Comment by skissue** [comment]
Merged the fix into main, so it should be available on MELPA & MELPA Stable after their next rebuild.
